language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get golang.org/x/tools/cmd/cover || true
  - go get code.google.com/p/go.tools/cmd/cover || true
  - go get github.com/robertkrimen/otto
  - go get github.com/howeyc/fsnotify
  - go get github.com/robfig/gettext/po
  - go get github.com/robfig/soy
script:
  - go test github.com/$TRAVIS_REPO_SLUG/...
